"""Created new tables, pPost and Tag

Revision ID: 11105fd8290f
Revises: baf85a606404
Create Date: 2023-08-24 19:28:10.047879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11105fd8290f'
down_revision = 'baf85a606404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint('shows_series_uid_fkey', type_='foreignkey')
        batch_op.drop_column('series_uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('shows_series_uid_fkey', 'series', ['series_uid'], ['uid'])

    op.drop_table('posts')
    op.drop_table('tags')
    # ### end Alembic commands ###
