"""empty message

Revision ID: 1f3bd9e69427
Revises: fe0f9aedd21d
Create Date: 2023-08-15 20:13:07.354047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3bd9e69427'
down_revision = 'fe0f9aedd21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(length=32),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(length=32),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
