"""Show table added

Revision ID: baf85a606404
Revises: 1f3bd9e69427
Create Date: 2023-08-23 21:02:56.493027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf85a606404'
down_revision = '1f3bd9e69427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('series_uid', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'series', ['series_uid'], ['uid'])
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('series_uid')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
