"""Why is usersname not being detected

Revision ID: c1d4a4c8de0e
Revises: 36bc28a5cd05
Create Date: 2023-08-25 21:06:09.553487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1d4a4c8de0e'
down_revision = '36bc28a5cd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combined_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combined_table',
    sa.Column('abrv', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('abbreviation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('productionStartYear', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productionEndYear', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('originalRunStartDate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('originalRunEndDate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seasonsCount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('episodesCount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('featureLengthEpisodesCount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productionCompany', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('originalBroadcaster', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('companies_uid', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
