"""Updating tables

Revision ID: dbe6221a7052
Revises: c1d4a4c8de0e
Create Date: 2023-09-01 22:41:55.541187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe6221a7052'
down_revision = 'c1d4a4c8de0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species_uid', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location_uid', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'species', ['species_uid'], ['uid'])
        batch_op.create_foreign_key(None, 'locations', ['location_uid'], ['uid'])

    with op.batch_alter_table('spacecraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spacecraftClass_uid', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'spacecraftClasses', ['spacecraftClass_uid'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spacecraft', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('spacecraftClass_uid')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_uid')
        batch_op.drop_column('species_uid')

    # ### end Alembic commands ###
