"""Added PostTag table

Revision ID: f7dd3cda60e7
Revises: 11105fd8290f
Create Date: 2023-08-24 21:45:03.644162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7dd3cda60e7'
down_revision = '11105fd8290f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combined_table')
    with op.batch_alter_table('posts_tags', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))

    op.create_table('combined_table',
    sa.Column('abrv', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('abbreviation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('productionStartYear', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productionEndYear', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('originalRunStartDate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('originalRunEndDate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seasonsCount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('episodesCount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('featureLengthEpisodesCount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productionCompany', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('originalBroadcaster', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('companies_uid', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
